name: iOS Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build iOS Release
      - name: Build iOS
        run: flutter build ios --release --no-codesign

      # Step 5: Create the IPA
      - name: Generate IPA file
        run: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/exportOptions.plist

      # Step 6: Upload the IPA as an artifact (optional)
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-release-ipa
          path: build/ios/ipa
